defaults:
  - generator/generator_mild@generator_mild
  - generator/generator_severe@generator_severe
_target_: BrainID.datasets.fetal_id_synth.BrainIDFetalSynthDataset
bids_path: /media/tsanchez/tsanchez_data/data/fetal_dHCP/derivatives/derivatives/resampled0p5
seed_path: /media/tsanchez/tsanchez_data/data/fetal_dHCP/derivatives/derivatives/seeds0p5
sub_list: null
load_image: True
image_as_intensity: False
n_mild_samples: 2
n_severe_samples: 2 