_target_: lightning.pytorch.trainer.Trainer

default_root_dir: ${paths.output_dir}

min_epochs: 10 # prevents early stopping
max_steps: 80000

accelerator: gpu
devices: 1

# mixed precision for extra speed-up
precision: "16-mixed"
deterministic: False

val_check_interval: 1000
log_every_n_steps: 25 #  How often to log within steps. Default: 50.
check_val_every_n_epoch: null 
