defaults:
  - fetalsyngen/synth_train
  - default_train
#  - default_val
#  #- submit
  - _self_
  
## job specific set ups ##
job_name: anat-uncertainty
exp_name: feat-anat
#init_method: "tcp://localhost:9992"

device: "cuda:0"
device_generator:
num_workers: 1

task: feat-anat
dataset_name: {'train': 'synth_id', 'test': 'real_dataset'}

eval_only: False 
debug: False 

resume: False
reset_epoch: False 
resume_optim: True
ckp_path: 
#train_fetal_cfg: '/home/tsanchez/Documents/mial/repositories/FetalSynthGen/configs'

#lr_drops: [70,85]

batch_size: 1


train_patch: True
patch_size: 128
patch_boundary: 20
patch_per_subject: 3
#log_itr: 20
#vis_itr: 1
