defaults:
  - data: task_qc
  - model: qc_baseline
  - paths: default
  - trainer: default
  - logger: wandb
  - callbacks: task_qc
#  - default_val
#  #- submit
  - _self_
  
## job specific set ups ##
job_name: qc_run
exp_name: qc

device: "cpu"
device_generator: "cpu"
num_workers: 1

eval_only: False 
debug: False 

resume: False
reset_epoch: False 
resume_optim: True
resume_lr_scheduler: True
freeze_feat: False
load_backbone: False
feat_ckpt:
#train_fetal_cfg: '/home/tsanchez/Documents/mial/repositories/FetalSynthGen/configs'
resume_training: False
resume_ckpt: 
## paths 
out_dir: outs/BrainID


supervised_seg_cnn_weights:  
feat_ext_ckp_path:
ckp_path:

## training params
start_epoch: 0
train_itr_limit: # if not None, it sets the max itr per epoch 
train_subset: #0.2

n_epochs: 400


## testing params
test_itr_limit: 
test_subset:


seed: 6546
# distributed training parameters
# number of distributed processes
world_size: 1
# url used to set up distributed training
dist_url: env://


## logging intervals
val_epoch: 100000 # must be multiplicable by save_model_epoch

log_itr: 50
vis_itr: 5000


#log_itr: 20
#vis_itr: 1
