defaults:
  - data: task_qc
  - model: qc_model
  - paths: default
  - trainer: default
  - logger: wandb
  - callbacks: task_qc
  - _self_
  
## job specific set ups ##

device: "cuda:0"
device_generator:
logger:
  wandb:
    name: "QC_ft_no_aug"
    project: brainid_qc

eval_only: False 
debug: False 

freeze_feat: False
load_backbone: True
feat_ckpt: /home/tsanchez/Documents/mial/repositories/Brain-ID/outputs/best_feat_marinas/last.ckpt
#train_fetal_cfg: '/home/tsanchez/Documents/mial/repositories/FetalSynthGen/configs'
resume_training: False
resume_ckpt: /home/tsanchez/Documents/mial/repositories/Brain-ID/outputs/2025-05-09/09-58-15/checkpoints/last.ckpt
## paths 
out_dir: outs/BrainID/QC

n_epochs: 400


## testing params
test_itr_limit: 
test_subset:


seed: 6546
# distributed training parameters
# number of distributed processes
world_size: 1
# url used to set up distributed training
dist_url: env://


## logging intervals
val_epoch: 100000 # must be multiplicable by save_model_epoch

log_itr: 50
vis_itr: 5000

wandb:
  project: "brainid_qc"
  name: null

#log_itr: 20
#vis_itr: 1
