defaults:
  - data: task_qc_baseline
  - model: qc_baseline
  - paths: default
  - trainer: default
  - logger: wandb
  - callbacks: task_qc_baseline
#  - default_val
#  #- submit
  - _self_
  
## job specific set ups ##
logger:
  wandb:
    name: "QC_baseline_Conv3_fc2"
    project: brainid_qc
job_name: qc_run_baseline
exp_name: qc_baseline
device: "cuda:0"

data:
  num_workers: 1
eval_only: False 
debug: False 

resume: False
reset_epoch: False 
resume_optim: True
resume_lr_scheduler: True
freeze_feat: False
load_backbone: False
feat_ckpt:
#train_fetal_cfg: '/home/tsanchez/Documents/mial/repositories/FetalSynthGen/configs'
resume_training: False
resume_ckpt: 
## paths 
out_dir: outs/BrainID



n_epochs: 400



seed: 6546




