_target_: BrainID.models.lightning_module.BrainIDModel
task: "feat-anat"
backbone:
  _target_:  BrainID.models.unet3d.model.UNet3D
  in_channels: 1 
  f_maps: 48
  f_maps_supervised_seg_cnn: 48
  num_groups: 8
  num_levels: 5
  layer_order: 'gcl'
  final_sigmoid: False
head:
  _target_: BrainID.models.head.IndepHead
  f_maps_list: [48]
  out_channels: 
    image: 1
    contrast_image: 1
    seg: 10
  is_3d: True
  out_feat_level: -1 
processor: []
criterion:
  _target_: BrainID.models.criterion.SetMultiCriterion
  device: ${device}
  params_dict:
    uncertainty: # only for recon or sr (regression tasks); options: { gaussian, laplace }
    bias_field_log_type: l2 # l1 or l2 
  loss_dict:
    image:  0.5
    image_grad: 0.5
    seg_dice_ce:  1.0
    artifact: 0.5
    artifact_grad: 0.5
  uncertainty_weigthing: True


optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 0.0001
  weight_decay: 0.0001
  betas: [0.9, 0.98]
  fused: true

#scheduler:
#  _target_: BrainID.utils.scheduler.PolynomialWarmupDecayLR
#  _partial_: true
#  warmup_epochs: 10
#  total_epochs: 400
#  power: 0.9
# scheduler:
#   _target_: torch.optim.lr_scheduler.MultiStepLR
#   _partial_: true
#   milestones: [300, 350]
#   gamma: 0.1
scheduler:
  _target_ torch.optim.lr_scheduler.ReduceLROnPlateau
  mode: min
  