_target_: BrainID.models.lightning_module.BrainIDModel
task: "feat-anat"
backbone:
  _target_:  BrainID.models.unet3d.model.UNet3D
  in_channels: 1 
  f_maps: 32
  f_maps_supervised_seg_cnn: 32
  num_groups: 8
  num_levels: 5
  layer_order: 'gcl'
  final_sigmoid: False
head:
  _target_: BrainID.models.head.IndepHead
  f_maps_list: [32]
  out_channels: 
    image: 1
  is_3d: True
  out_feat_level: -1 
processor: []
criterion:
  _target_: BrainID.models.criterion.SetMultiCriterion
  n_samples: ${data.n_all_samples}
  device: ${device}
  params_dict:
    uncertainty: # only for recon or sr (regression tasks); options: { gaussian, laplace }
    bias_field_log_type: l2 # l1 or l2 
  loss_dict:
    image:  1.
    image_grad: 1.

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 0.0001
  weight_decay: 0
scheduler:
  _target_: torch.optim.lr_scheduler.MultiStepLR
  _partial_: true
  milestones: [300, 350]
  gamma: 0.1