_target_: BrainID.models.baselines.baseline_lightning.BaselineModel
task: "qc"
n_batches_vis: 5
model:
  _target_: BrainID.models.baselines.qc.Conv3_FC2
  input_size: [1, 256, 256, 256]
  norm: "instance"
  gpu: True
  output_size: 2
  dropout: 0.1
# model:
#  _target_: BrainID.models.baselines.qc.ModelWrapper
#  model:
#    _target_: monai.networks.nets.DenseNet121
#    spatial_dims: 3
#    in_channels: 1
#    out_channels: 2
#    norm: "instance"
criterion:

  _target_: BrainID.models.criterion.SetScalarCriterion
  device: ${device}
  loss_dict:
    ce:  1.

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 0.0001
  weight_decay: 1e-3
scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  patience: 5
  factor: 0.5