_target_: BrainID.models.baselines.baseline_lightning.BaselineModel
task: "qc"
n_batches_vis: 5
model:
  _target_: BrainID.models.baselines.qc.Conv5_FC3
  input_size: [1, 256, 256, 256]
  norm: "instance"
  gpu: True
  output_size: 2
  dropout: 0.5
  
criterion:

  _target_: BrainID.models.criterion.SetScalarCriterion
  device: ${device}
  loss_dict:
    ce:  1.

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 0.0001
  weight_decay: 0
scheduler:
  _target_: torch.optim.lr_scheduler.MultiStepLR
  _partial_: true
  milestones: [300, 350]
  gamma: 0.1