_target_: BrainID.models.lightning_module.BrainIDModel
task: "seg"
n_batches_vis: 5
backbone:
  _target_:  BrainID.models.unet3d.model.UNet3D
  in_channels: 1 
  f_maps: 48
  f_maps_supervised_seg_cnn: 48
  num_groups: 8
  num_levels: 5
  layer_order: 'gcl'
  final_sigmoid: False
head:
  _target_: BrainID.models.head.IndepHead
  f_maps_list: [48]
  out_channels: 
    seg: 10 # 10 classes.
  is_3d: True
  out_feat_level: -1 
  
processor: []
criterion:
  _target_: BrainID.models.criterion.SetMultiCriterion
  
  device: ${device}
  params_dict:
    uncertainty: 
    bias_field_log_type: 
  loss_dict:
    seg_dice_ce:  1.

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 0.0001
  weight_decay: 0
scheduler:
  _target_: torch.optim.lr_scheduler.MultiStepLR
  _partial_: true
  milestones: [300, 350]
  gamma: 0.1