defaults:
  - early_stopping
  - model_summary
  - rich_progress_bar
  # - lr_finder
  - lr_monitor
  - visualizer
  - feature_visualizer
  - _self_

model_checkpoint_val:
  _target_: lightning.pytorch.callbacks.ModelCheckpoint
  dirpath: ${paths.output_dir}/checkpoints
  filename: "epoch_{epoch:03d}_val_dsc_{val/loss:.4f}_step_{step}"
  monitor: "val/loss"
  mode: "min"
  save_last: True
  auto_insert_metric_name: False

model_checkpoint_train:
  _target_: lightning.pytorch.callbacks.ModelCheckpoint
  dirpath: ${paths.output_dir}/checkpoints
  filename: "last_train"
  every_n_epochs: 1
  save_last: False
  save_on_train_epoch_end: True
  auto_insert_metric_name: False

seg_visualizer:
  _target_: BrainID.utils.visualizer.SegValidationSnapshot
  output_dir: ${paths.output_dir}/snapshots
  num_slices: 7

early_stopping:
  monitor: "val/loss"
  patience: 200
  mode: "min"

model_summary:
  max_depth: 1