defaults:
  - model_checkpoint
  - early_stopping
  - model_summary
  - rich_progress_bar
  - lr_monitor
  - _self_

qc_metrics:
  _target_: BrainID.utils.metrics.QCMetrics
  on_train: True
  on_val: True
  on_test: True

visualizer:
  _target_: BrainID.utils.visualizer.QCValidationSnapshot
  output_dir: ${paths.output_dir}/snapshots
  num_slices: 7
  vis_feat: False

model_checkpoint_val:
  dirpath: ${paths.output_dir}/checkpoints
  filename: "epoch_{epoch:03d}_val_dsc_{val/loss:.4f}_step_{step}"
  monitor: "val/loss"
  mode: "min"
  save_last: True
  auto_insert_metric_name: False

model_checkpoint_train:
  dirpath: ${paths.output_dir}/checkpoints
  filename: "last_train"
  save_top_k: 1
  every_n_epochs: 1
  auto_insert_metric_name: False

early_stopping:
  monitor: "val/loss"
  patience: 200
  mode: "min"

model_summary:
  max_depth: 1