defaults:
  - model_checkpoint
  - early_stopping
  - model_summary
  - rich_progress_bar
  - lr_monitor
  - _self_

qc_metrics:
  _target_: BrainID.utils.metrics.QCMetrics
  on_train: True
  on_val: True
  on_test: True

prediction_test:
  _target_: BrainID.utils.metrics.PredictionWriterCallback
  output_dir: ${paths.output_dir}
  filename: predictions_test.csv

visualizer:
  _target_: BrainID.utils.visualizer.QCValidationSnapshot
  output_dir: ${paths.output_dir}/snapshots
  num_slices: 7
  vis_feat: False

model_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  filename: "epoch_{epoch:03d}_val_auc_{val/auroc_epoch:.4f}_step_{step}"
  monitor: "val/auroc_epoch"
  mode: "max"
  save_last: True
  auto_insert_metric_name: False

save_predictions:
  _target_: BrainID.utils.callbacks.LogPredictionsCallback
  output_dir: ${paths.output_dir}/eval
  output_file: "predictions.csv"

early_stopping:
  monitor: "val/auroc_epoch"
  patience: 3
  mode: "max"

model_summary:
  max_depth: 1